from app.models import db, Review, ReviewImage, environment, SCHEMA
import app.s3 as s3

# Adds a demo user, you can add other users here if you want
def seed_reviews():

    review1 = Review(user_id=2, product_id=1, rating=5, headline="Unleash the Power: The ultimate Batteries!", body="I recently purchased the Amazon Basics 36 Pack AA Alkaline Batteries and I must say, I am beyond impressed! These batteries are a true powerhouse, providing long-lasting and reliable power to all of my devices. Whether it's a remote control, wireless mouse, or even a children's toy, these batteries get the job done and keep my devices running smoothly./nWhat I love most about these batteries is their impressive lifespan. I have used them for weeks on end without having to replace them, which saves me time and money in the long run. And even better, they come in a pack of 36, ensuring that I always have spare batteries on hand when I need them./nThe Amazon Basics Batteries are also incredibly affordable, making them a great value for their quality and reliability. They are the perfect solution for anyone looking for a cost-effective way to power their devices without sacrificing performance.")
    review2 = Review(user_id=3, product_id=1, rating=4, headline="Great Battery for the money", body="Price is great compared to say Duracell or Energizer. I have been buying these a long time and still get duracell or energizer from time to time when they have a good sale. I have never had an issue with dead batteries as I have heard some reviewers mention and I have been getting these for years and I am sure I have used well over a few hundred Amazon batteries and never had a dead on arrival. As for their performance I have to admit I have never done any kind of real test to compare but I will say my impression is they may not last as long as Duracell or Energizer but the difference is not worth the price difference in my opinion. I bought these in my subscribe and save accont and at .22 a battery I don't think you can go wrong. So I would give these batteries a shot.")
    review3 = Review(user_id=4, product_id=2, rating=5, headline="These towels are nothing short of amazing", body="Holds true to the description! In my bathroom, I tend to have an issue with towels getting the nasty mildew smell do to poor air flow. I haven't had mine fade after washing and drying them. They soak up water well in my opinion.")
    review4 = Review(user_id=5, product_id=2, rating=3, headline="Pretty functional once I got the lint under control", body="First time I ordered them ,The start was a bit rough , first few uses were so bad . My kid grabbed one and then started crying because of all the black lint stuck on o them. They took another bath to wash off the lint . I prewashed them too . By the 4th wash it got much better . Stil a little bit of lint but . It's a decent size . If they had not shed tons of lint I woulda given 5 stars . It's a 4 star purchase . Maybe 3.5 but I'm gonna round up .When I wrote the review for these I had only bought them once . When I was looking the listing I ended up buying another set from the amazon warehouse for $7 shipped for the set of 2. I figured since I knew they shed I'd just wash them a few times before using them . Id done 1 pre wash and it wasn't enough to stop it from shedding so when I ordered them a second time I had a plan and didn't mind the extra effort because the price was a deal . I realize the warehouse item I bought was not brand new but it said new but in different packaging then it originally came in . I see people get mad when they receive repackaged items from Amazon warehouse ")
    review5 = Review(user_id=6, product_id=3, rating=5, headline=" Incredible Value for the Best Hangers!", body="These hangers are incredible! They keep my clothes from slipping off in the closet - so I have been able to hang all of my camis, silks and every kind of top that typically slips off a regular hanger. And, because of their unusual shape, they haven’t left a funky hanger dent in the shoulder of my tops. I couldn't believe how many were included in a pack too! I was able to get everything I needed hung by ordering 1 pack of 50. Because these hangers keep things from slipping so well, I would not use them to hang pants. Because of their slip resistance, I found it difficult to thread them through the opening. But these are working so well for what I needed!")
    review6 = Review(user_id=7, product_id=3, rating=2, headline="Mixed Review", body="For those items of clothes that never stay on a hanger, these are indeed perfect. The velvet acts as velco with most fabrics that I tried. I will absolutely be using these for those items. I ordered the navy velvet pack of 50. For day-to-day regular clothing, these hangers would put me over the edge. Since the velvet acts as velco, everything sticks. If you like your clothing to hang neatly on the hanger, each shoulder will have to be placed just so. There is no sliding this hanger into a shirt. Think flannel sheets with flannel jammies. Just a lesson in frustration, lol. Broke the first hanger I used pushing it too hard into a crewneck sweatshirt. They do bend a bit but bust quite easily. Oh, and drop one on the floor, it will gather every cat hair, piece of lint, thread whatever from the location it lands on. Overall, I'm glad I do have some of these types of hangers for certain clothing, but not good in my opinion for every day. UPDATE: I changed my review from 3 to 4 stars for the simple fact that I do reach for these for certain articles of clothing more than I expected.")
    review7 = Review(user_id=8, product_id=4, rating=5, headline="Just as good as name brand", body="I purchased this to use in my home gym. It is good quality. Doesn't slip when gripping it. Excellent for weighted ab exercises.")
    review8 = Review(user_id=9, product_id=4, rating=1, headline="This ball is covered in smelly oil", body="Received medicine ball on time. Opened box and ball came in a plastic bag. Took the ball out of the bag and it was covered in smelly oil. The whole ball was slippery. I immediatly made a hot sink with soapy water and washed the ball thoroughly. Once dry, the smell was still present - not as bad. I like the look and the ball works great and seems super tough. I have used it for a few workouts now, and I find my hands have a residue on them after - which has the same unpleasant smell, and anywhere the ball has been on our laminate flooring is a super slippery spot. Both my dog and child have seriously wiped out. So, not overly pleased with this oily residue that is still coming out of it.")
    review9 = Review(user_id=1, product_id=5, rating=5, headline="Amazing fragrance", body="I loved the fragrance of this product and it lasted long in my car. Definitely recommend buying it.")
    review10 = Review(user_id=2, product_id=5, rating=4, headline="Nice smell", body="Smell began to fade sooner than I expected. Smell is nice for as long as they lasted. (about a month)")
    review11 = Review(user_id=3, product_id=6, rating=5, headline="Perfect!", body="Used this to diagnose my check engine light. It said I need a new camshaft sensor. I went to the store and bought one, changed it out and boom! Check engine light came right off. Very accurate!!")
    review12 = Review(user_id=4, product_id=6, rating=3, headline="3.0 out of 5 starsDoes NOT Find Permanent Codes", body="Disappointed because I bought this to make sure a Permanent code was cleared so I could pass smog. The device found no codes so I thought I was ok, but nope, failed smog a second time, wasted the money on the smog check. Permanent codes cannot be cleared by any tool, only the vehicle itself can clear it after enough 'drive cycle' conditions happen./nHowever.. the device does check sensor readiness, so I should have used that as a clue.")
    review13 = Review(user_id=5, product_id=7, rating=5, headline="Great device for the size!", body="I had purchased a device like this one a couple years ago, but the end broke. So for the price and how handy it is, I just ordered a new one. This one is just a bit smaller but does the same thing. I keep it right underneath the back side of the passenger seat and use it quite often to keep my tires inflated to the proper size. I also use it for my bicycle. It works great, and saves trying to find an air compressor at a station somewhere.")
    review14 = Review(user_id=6, product_id=7, rating=2, headline=" Compressed my wallet better than it does air.", body="Keep scrolling.This is not the compressor you want.It's plastic fittings are too cheap to take seriously.150 PSI? Hahaha. No. It struggles after 30 PSI.It tries so hard the hose keeps coming off (see pic).Highly recommend this as a gift for someone you hate.")
    review15 = Review(user_id=7, product_id=8, rating=5, headline="5.0 out of 5 stars Excellent!", body="The trickiest part is the installation. If your current car cup holder has a deep slot for a mug handle (for instance), you have to hold the expanders from turning while you tighten this cup holder extender. Otherwise, one of the three expanders will end up in the car's 'coffee mug handle slot' and render the extender loose and useless. Once you get it anchored in, you're golden :-) I would highly recommend this Car Cup Holder Expander Adapter.")
    review16 = Review(user_id=9, product_id=8, rating=1, headline="Quality could be way better", body="Quality: Quality is ok. Quite flimsy but a little sturdiness makes it ok. Even paid at 39$ in promo. Quality could be a ton better for the price. Cheap plastic and I feel like it could easily break. I will personally keep it to see how it does since I work on the road and absolutely need a solution for large water bottles. Otherwise, I would have returned it.")
    review17 = Review(user_id=8, product_id=9, rating=5, headline=" Impressed with build quality and did it's job.", body="I have only used it once, but appears to be well made and did it's job. I chose this over others because of the design and case for ease of storage in my vehicle. I have an older secondary vehicle that I have not driven in 4 months with a completely dead battery (I should have disconnected the car battery). This Nexpow jump started it up on the first attempt. I had previously attempted to start it with my 12 year old heavy jump starter and discovered it finally bit the dust. To be able to do the same job with something so much lighter that I can store in my trunk or glove box is impressive. It comes with a nice case, jump start cable attachment, and usb cable to charge it (the unit came 75 percent charged - 3 lights out of 4).")
    review18 = Review(user_id=5, product_id=9, rating=4, headline="Defective Clamp separated after use, replaced item", body="This battery charger seems quite powerful. I've owned several such items. The only problem is it's cable was defective, and separated after plugging into the pack then removing. Others seem to have had the same problem as written in the questions. I have reached out to seller requesting a replacement, and will update depending on response.Update: I reached out to seller via Amazon, and seller sent me a complete replacement. While this was not necessary, and only the cable was defective, it is appreciated. I've updated my feedback from 1 to 4 stars for the quality of the seller, and the replacement cable (and battery) seems to be in order.")
    review19 = Review(user_id=1, product_id=10, rating=5, headline="Good for depression and low energy sufferers", body="I watched a couple videos on youtube that blasted this thing because you could use a pan and make a breakfast sandwich in about the same amount of time as this machine.\nHowever, I am very happy with it. When I'm rushing in the morning before work, it's nice that I can throw everything in the cooker, go get myself ready, wrap the finished sandwich in foil, and throw it in my purse for later. At 6:30am I'm not going to mess with clanking pans and utensils and wake my family up.")
    review20 = Review(user_id=3, product_id=10, rating=5, headline="That was delicious", body="I cut up left over pizza , thawed/drained veggies, and eggs to make the pizza sandwiches. I read a review that said to buy the double cup , and I agree . It's nice to have both ready after 5 min . :)")
    review21 = Review(user_id=4, product_id=11, rating=5, headline="Works perfectly", body="Got to a place my 20 year old George Foreman. Pretty much identical to my last one. Just a bit smaller. And I like it the Panthers smaller")
    review22 = Review(user_id=5, product_id=11, rating=2, headline=" DO NOT BUY", body="Abstract: The new non-stick coating just does not work.")
    review23= Review(user_id=6, product_id=12, rating=5, headline="So far so good…", body="This just arrived and I tested it out and so far I love it. I think this can replace all my other gadgets and this will be enough. I’m not ready to let go of my ceramic mandoline yet, but I think I will be able to eventually. The size of this is not so big. When it arrived I thought it was going to be big because of the packaging, but it's a perfect size. I can store it no problem. I have to see if this is a good grater, so I can get rid of my hand grater eventually too. But I’m not sure just yet. Cuts potatoes in 3 difference sizes no problem, also onions was a nice chopping size")
    review24 = Review(user_id=8, product_id=12, rating=1, headline="Sharp af!", body="I straight filleted myself. I'm actually writing this review after leaving the ER.")
    review25 = Review(user_id=9, product_id=13, rating=5, headline="Easy and convenient!", body="This was delivered today and I was extremely excited to use it. Magic bullet is the best product I've ordered so far! Comes with 3 jars, 3 lids, every jar can be used on the blender because of the detachable blade!!!! Jars are smaller than I expected but got 3 of them and I am happy :)")
    review26 = Review(user_id=1, product_id=13, rating=4, headline="We've been using this multiple times a day", body="This is ridiculously easy to use. Screw the blade on and go. If you need to move something down towards the blade, it's already completely closed so you can shake it and pop it straight back on there. When you're done, you rinse the blade (also ridiculously easy) and you're good to go again. I will admit that I fall below average on blender usage, so ease of use and minimal risk of creating a mess were key in the decision process. There hasn't been a day that we haven't used this at least twice because it takes like 2 minutes start to finish, including clean up.")
    review27 = Review(user_id=2, product_id=14, rating=5, headline="Yes, this CAN make pancakes!", body="Perfect for my Keto pancakes! Alot more fuller than cooking in a pan. Very fluffy, not burnt at all on either side, and cooked all the way through. It did take about 7-10 min though, but Worth the wait. I did run some olive oil with a napkin on both sides of the heating plates, not sure if that was needed or not, but did it anyway.")
    review28 = Review(user_id=3, product_id=14, rating=3, headline="Cooking Temperature is not HOT enough.", body="I ordered this cooker to bake a specific bread because it was rated at 1440 watts and I needed that heat for the crusts on the bread, However the cooker you sent me is only rated at 750 watts. I tried using it and it does not get hot enough. your ad is misleading and wrong..!!!")
    review29 = Review(user_id=4, product_id=15, rating=5, headline="Lo mejor", body="Gracias me llegaron rápido 😁")
    review30 = Review(user_id=5, product_id=15, rating=2, headline="Horrible Packaging Change!", body="I want to keep these reviews coming so Pampers knows that they messed up.I, as well as other parents, hate the recent packaging change on these refills. If you're like me, you just bought a box of these out of habit and then were dismayed when you opened it up... Perhaps a look of incredulity passed over your face as you inspected your purchase and didn't see the shiny resealable sticker on the top of each wipe package. Then you saw the words "Pull open or cut at sides" printed near the edge, with cute little scissors and a dotted line showing you where you are supposedly expected to open your wipes to use.As")
    review31 = Review(user_id=6, product_id=16, rating=5, headline="Great Buy!", body="I have bought about 3 boxes bow from this seller and still going good. All wipes comes in different package designs each time but have all been pretty good. The pouches are full to capacity and the wipes are thick and stay wet until empty. Will definitely continue to buy more especially for the price too!")
    review32 = Review(user_id=8, product_id=16, rating=1, headline="So disappointed Quality is so Bad!", body="I usually purchase these but I don't know if I got a defective box or quality just went down, suppose to be for sensitive skin an these wipes are literally scratchy before noticing both my babies 2 and 1 said ouch to these I ran my finger through one and it's literally scratchy walmart flushable equate wipes are better than these, the box was different than usual so it might just be that batch I'll prob switch brands for now or look elsewhere.")
    review33 = Review(user_id=9, product_id=17, rating=5, headline="Leaves skin clean and soft", body="Neutrogena make up remover wipes not only take the make up off first wipe, but leaves my skin feeling soft. I highly recommend this product to anyone who loves wearing makeup, or just needs to clean their face from everyday dirt!")
    review34 = Review(user_id=1, product_id=17, rating=5, headline="Best Travel Accessory!!!", body="I love these makeup remover wipes. They are easy to use and carry. I get the best results when trying to remove my eye make up.")
    review35 = Review(user_id=4, product_id=18, rating=5, headline="", body="")
    review36 = Review(user_id=2, product_id=18, rating=4, headline="", body="")
    review37 = Review(user_id=3, product_id=19, rating=5, headline="", body="")
    review38 = Review(user_id=4, product_id=19, rating=3, headline="", body="")
    review39 = Review(user_id=5, product_id=20, rating=5, headline="", body="")
    review40 = Review(user_id=6, product_id=20, rating=2, headline="", body="")
    review41 = Review(user_id=7, product_id=21, rating=5, headline="", body="")
    review42 = Review(user_id=8, product_id=21, rating=1, headline="", body="")
    review43 = Review(user_id=9, product_id=22, rating=5, headline="", body="")
    review44 = Review(user_id=1, product_id=22, rating=5, headline="", body="")
    review45 = Review(user_id=2, product_id=23, rating=5, headline="", body="")
    review46 = Review(user_id=3, product_id=23, rating=4, headline="", body="")
    review47 = Review(user_id=4, product_id=24, rating=5, headline="", body="")
    review48 = Review(user_id=5, product_id=24, rating=3, headline="", body="")
    review49 = Review(user_id=6, product_id=25, rating=5, headline="", body="")
    review50 = Review(user_id=2, product_id=25, rating=2, headline="", body="")
    review51 = Review(user_id=6, product_id=26, rating=5, headline="", body="")
    review52 = Review(user_id=9, product_id=26, rating=1, headline="", body="")
    review53 = Review(user_id=1, product_id=27, rating=5, headline="", body="")
    review54 = Review(user_id=2, product_id=27, rating=5, headline="", body="")
    review55 = Review(user_id=3, product_id=28, rating=5, headline="", body="")
    review56 = Review(user_id=4, product_id=28, rating=4, headline="", body="")
    review57 = Review(user_id=5, product_id=29, rating=5, headline="", body="")
    review58 = Review(user_id=6, product_id=29, rating=3, headline="", body="")
    review59 = Review(user_id=7, product_id=30, rating=5, headline="", body="")
    review60 = Review(user_id=8, product_id=30, rating=2, headline="", body="")
    review61 = Review(user_id=9, product_id=31, rating=5, headline="", body="")
    review62 = Review(user_id=1, product_id=31, rating=1, headline="", body="")
    review63 = Review(user_id=2, product_id=32, rating=5, headline="", body="")
    review64 = Review(user_id=3, product_id=32, rating=5, headline="", body="")
    review65 = Review(user_id=4, product_id=33, rating=5, headline="", body="")
    review66 = Review(user_id=5, product_id=33, rating=4, headline="", body="")
    review67 = Review(user_id=6, product_id=34, rating=5, headline="", body="")
    review68 = Review(user_id=3, product_id=34, rating=3, headline="", body="")
    review69 = Review(user_id=1, product_id=35, rating=5, headline="", body="")
    review70 = Review(user_id=9, product_id=35, rating=2, headline="", body="")
    review71 = Review(user_id=1, product_id=36, rating=5, headline="", body="")
    review72 = Review(user_id=2, product_id=36, rating=1, headline="", body="")
    review73 = Review(user_id=3, product_id=37, rating=5, headline="", body="")
    review74 = Review(user_id=4, product_id=37, rating=5, headline="", body="")
    review75 = Review(user_id=5, product_id=38, rating=5, headline="", body="")
    review76 = Review(user_id=6, product_id=38, rating=4, headline="", body="")
    review77 = Review(user_id=7, product_id=39, rating=5, headline="", body="")
    review78 = Review(user_id=8, product_id=39, rating=3, headline="", body="")
    review79 = Review(user_id=9, product_id=40, rating=5, headline="", body="")
    review80 = Review(user_id=1, product_id=40, rating=2, headline="", body="")
    review81 = Review(user_id=2, product_id=41, rating=5, headline="", body="")
    review82 = Review(user_id=3, product_id=41, rating=1, headline="", body="")
    review83 = Review(user_id=4, product_id=42, rating=5, headline="", body="")
    review84 = Review(user_id=5, product_id=42, rating=5, headline="", body="")
    review85 = Review(user_id=6, product_id=43, rating=5, headline="", body="")
    review86 = Review(user_id=9, product_id=43, rating=4, headline="", body="")
    review87 = Review(user_id=3, product_id=44, rating=5, headline="", body="")
    review88 = Review(user_id=9, product_id=44, rating=3, headline="", body="")
    review89 = Review(user_id=8, product_id=45, rating=5, headline="", body="")
    review90 = Review(user_id=2, product_id=45, rating=2, headline="", body="")
    review91 = Review(user_id=3, product_id=46, rating=5, headline="", body="")
    review92 = Review(user_id=4, product_id=46, rating=1, headline="", body="")
    review93 = Review(user_id=5, product_id=47, rating=5, headline="", body="")
    review94 = Review(user_id=6, product_id=47, rating=5, headline="", body="")
    review95 = Review(user_id=7, product_id=48, rating=5, headline="", body="")
    review96 = Review(user_id=8, product_id=48, rating=4, headline="", body="")
    review97 = Review(user_id=9, product_id=49, rating=5, headline="", body="")
    review98 = Review(user_id=1, product_id=49, rating=3, headline="", body="")
    review99 = Review(user_id=2, product_id=50, rating=5, headline="", body="")
    review100 = Review(user_id=3, product_id=50, rating=2, headline="", body="")
    review101 = Review(user_id=4, product_id=51, rating=5, headline="", body="")
    review102 = Review(user_id=5, product_id=51, rating=1, headline="", body="")
    review103 = Review(user_id=6, product_id=52, rating=5, headline="", body="")
    review104 = Review(user_id=7, product_id=52, rating=5, headline="", body="")
    review105 = Review(user_id=8, product_id=53, rating=5, headline="", body="")
    review106 = Review(user_id=5, product_id=53, rating=4, headline="", body="")
    review107 = Review(user_id=9, product_id=54, rating=5, headline="", body="")
    review108 = Review(user_id=2, product_id=54, rating=3, headline="", body="")
    review109 = Review(user_id=3, product_id=55, rating=5, headline="", body="")
    review110 = Review(user_id=4, product_id=55, rating=2, headline="", body="")
    review111 = Review(user_id=5, product_id=56, rating=5, headline="", body="")
    review112 = Review(user_id=6, product_id=56, rating=1, headline="", body="")
    review113 = Review(user_id=7, product_id=57, rating=5, headline="", body="")
    review114 = Review(user_id=8, product_id=57, rating=5, headline="", body="")
    review115 = Review(user_id=9, product_id=58, rating=5, headline="", body="")
    review116 = Review(user_id=1, product_id=58, rating=4, headline="", body="")
    review117 = Review(user_id=2, product_id=59, rating=5, headline="", body="")
    review118 = Review(user_id=3, product_id=59, rating=3, headline="", body="")
    review119 = Review(user_id=4, product_id=60, rating=5, headline="", body="")
    review120 = Review(user_id=5, product_id=60, rating=2, headline="", body="")
    review121 = Review(user_id=6, product_id=61, rating=5, headline="", body="")
    review122 = Review(user_id=7, product_id=61, rating=1, headline="", body="")
    review123 = Review(user_id=8, product_id=62, rating=5, headline="", body="")
    review124 = Review(user_id=6, product_id=62, rating=5, headline="", body="")
    review125 = Review(user_id=7, product_id=63, rating=5, headline="", body="")
    review126 = Review(user_id=2, product_id=63, rating=4, headline="", body="")
    review127 = Review(user_id=3, product_id=64, rating=5, headline="", body="")
    review128 = Review(user_id=4, product_id=64, rating=3, headline="", body="")
    review129 = Review(user_id=5, product_id=65, rating=5, headline="", body="")
    review130 = Review(user_id=6, product_id=65, rating=2, headline="", body="")

    reviewImage1 = ReviewImage(review_id=1, url="")
    reviewImage2 = ReviewImage(review_id=1, url="")
    reviewImage3 = ReviewImage(review_id=1, url="")
    reviewImage4 = ReviewImage(review_id=2, url="")
    reviewImage5 = ReviewImage(review_id=2, url="")
    reviewImage6 = ReviewImage(review_id=2, url="")
    reviewImage7 = ReviewImage(review_id=2, url="")
    reviewImage8 = ReviewImage(review_id=3, url="")
    reviewImage9 = ReviewImage(review_id=3, url="")
    reviewImage10 = ReviewImage(review_id=3, url="")
    reviewImage11 = ReviewImage(review_id=4, url="")
    reviewImage12 = ReviewImage(review_id=4, url="")
    reviewImage13 = ReviewImage(review_id=4, url="")
    reviewImage14 = ReviewImage(review_id=4, url="")
    reviewImage15 = ReviewImage(review_id=5, url="")
    reviewImage16 = ReviewImage(review_id=5, url="")
    reviewImage17 = ReviewImage(review_id=5, url="")
    reviewImage18 = ReviewImage(review_id=6, url="")
    reviewImage19 = ReviewImage(review_id=6, url="")
    reviewImage20 = ReviewImage(review_id=6, url="")
    reviewImage21 = ReviewImage(review_id=6, url="")
    reviewImage22 = ReviewImage(review_id=7, url="")
    reviewImage23 = ReviewImage(review_id=7, url="")
    reviewImage24 = ReviewImage(review_id=7, url="")
    reviewImage25 = ReviewImage(review_id=8, url="")
    reviewImage26 = ReviewImage(review_id=8, url="")
    reviewImage27 = ReviewImage(review_id=8, url="")
    reviewImage28 = ReviewImage(review_id=8, url="")
    reviewImage29 = ReviewImage(review_id=9, url="")
    reviewImage30 = ReviewImage(review_id=9, url="")
    reviewImage31 = ReviewImage(review_id=9, url="")
    reviewImage32 = ReviewImage(review_id=10, url="")
    reviewImage33 = ReviewImage(review_id=10, url="")
    reviewImage34 = ReviewImage(review_id=10, url="")
    reviewImage35 = ReviewImage(review_id=10, url="")
    reviewImage36 = ReviewImage(review_id=11, url="")
    reviewImage37 = ReviewImage(review_id=11, url="")
    reviewImage38 = ReviewImage(review_id=11, url="")
    reviewImage39 = ReviewImage(review_id=12, url="")
    reviewImage41 = ReviewImage(review_id=12, url="")
    reviewImage42 = ReviewImage(review_id=12, url="")
    reviewImage43 = ReviewImage(review_id=12, url="")
    reviewImage44 = ReviewImage(review_id=13, url="")
    reviewImage45 = ReviewImage(review_id=13, url="")
    reviewImage46 = ReviewImage(review_id=13, url="")
    reviewImage47 = ReviewImage(review_id=14, url="")
    reviewImage48 = ReviewImage(review_id=14, url="")
    reviewImage49 = ReviewImage(review_id=14, url="")
    reviewImage50 = ReviewImage(review_id=14, url="")
    reviewImage51 = ReviewImage(review_id=15, url="")
    reviewImage52 = ReviewImage(review_id=15, url="")
    reviewImage53 = ReviewImage(review_id=15, url="")
    reviewImage54 = ReviewImage(review_id=16, url="")
    reviewImage55 = ReviewImage(review_id=16, url="")
    reviewImage56 = ReviewImage(review_id=16, url="")
    reviewImage57 = ReviewImage(review_id=16, url="")
    # reviewImage58 = ReviewImage(review_id=1, url="")
    reviewImage59 = ReviewImage(review_id=17, url="")
    reviewImage60 = ReviewImage(review_id=17, url="")
    reviewImage61 = ReviewImage(review_id=17, url="")
    reviewImage62 = ReviewImage(review_id=18, url="")
    reviewImage63 = ReviewImage(review_id=18, url="")
    reviewImage64 = ReviewImage(review_id=18, url="")
    reviewImage65 = ReviewImage(review_id=18, url="")
    reviewImage66 = ReviewImage(review_id=19, url="")
    reviewImage67 = ReviewImage(review_id=19, url="")
    reviewImage68 = ReviewImage(review_id=19, url="")
    reviewImage69 = ReviewImage(review_id=20, url="")
    reviewImage70 = ReviewImage(review_id=20, url="")
    reviewImage71 = ReviewImage(review_id=20, url="")
    reviewImage72 = ReviewImage(review_id=20, url="")
    reviewImage73 = ReviewImage(review_id=21, url="")
    reviewImage74 = ReviewImage(review_id=21, url="")
    reviewImage75 = ReviewImage(review_id=21, url="")
    reviewImage76 = ReviewImage(review_id=21, url="")
    reviewImage77 = ReviewImage(review_id=22, url="")
    reviewImage78 = ReviewImage(review_id=22, url="")
    reviewImage79 = ReviewImage(review_id=22, url="")
    reviewImage80 = ReviewImage(review_id=23, url="")
    reviewImage82 = ReviewImage(review_id=23, url="")
    reviewImage83 = ReviewImage(review_id=23, url="")
    reviewImage84 = ReviewImage(review_id=23, url="")
    reviewImage85 = ReviewImage(review_id=24, url="")
    reviewImage86 = ReviewImage(review_id=24, url="")
    reviewImage87 = ReviewImage(review_id=24, url="")
    reviewImage88 = ReviewImage(review_id=25, url="")
    reviewImage89 = ReviewImage(review_id=25, url="")
    reviewImage90 = ReviewImage(review_id=25, url="")
    reviewImage91 = ReviewImage(review_id=25, url="")
    reviewImage92 = ReviewImage(review_id=26, url="")
    reviewImage93 = ReviewImage(review_id=26, url="")
    reviewImage94 = ReviewImage(review_id=26, url="")
    reviewImage95 = ReviewImage(review_id=27, url="")
    reviewImage96 = ReviewImage(review_id=27, url="")
    reviewImage97 = ReviewImage(review_id=27, url="")
    reviewImage98 = ReviewImage(review_id=27, url="")
    reviewImage99 = ReviewImage(review_id=28, url="")
    reviewImage100 = ReviewImage(review_id=28, url="")
    reviewImage101 = ReviewImage(review_id=28, url="")
    reviewImage102 = ReviewImage(review_id=29, url="")
    reviewImage103 = ReviewImage(review_id=29, url="")
    reviewImage104 = ReviewImage(review_id=29, url="")
    reviewImage105 = ReviewImage(review_id=29, url="")
    reviewImage106 = ReviewImage(review_id=30, url="")
    reviewImage107 = ReviewImage(review_id=30, url="")
    reviewImage108 = ReviewImage(review_id=30, url="")
    reviewImage109 = ReviewImage(review_id=31, url="")
    reviewImage110 = ReviewImage(review_id=31, url="")
    reviewImage111 = ReviewImage(review_id=31, url="")
    reviewImage112 = ReviewImage(review_id=31, url="")
    reviewImage113 = ReviewImage(review_id=32, url="")
    reviewImage114 = ReviewImage(review_id=32, url="")
    reviewImage115 = ReviewImage(review_id=32, url="")
    reviewImage116 = ReviewImage(review_id=33, url="")
    reviewImage117 = ReviewImage(review_id=33, url="")
    reviewImage118 = ReviewImage(review_id=33, url="")
    reviewImage119 = ReviewImage(review_id=33, url="")
    reviewImage121 = ReviewImage(review_id=34, url="")
    reviewImage122 = ReviewImage(review_id=34, url="")
    reviewImage123 = ReviewImage(review_id=34, url="")
    reviewImage124 = ReviewImage(review_id=35, url="")
    reviewImage125 = ReviewImage(review_id=35, url="")
    reviewImage126 = ReviewImage(review_id=35, url="")
    reviewImage127 = ReviewImage(review_id=35, url="")
    reviewImage128 = ReviewImage(review_id=36, url="")
    reviewImage129 = ReviewImage(review_id=36, url="")
    reviewImage130 = ReviewImage(review_id=36, url="")
    reviewImage131 = ReviewImage(review_id=37, url="")
    reviewImage132 = ReviewImage(review_id=37, url="")
    reviewImage133 = ReviewImage(review_id=37, url="")
    reviewImage134 = ReviewImage(review_id=37, url="")
    reviewImage135 = ReviewImage(review_id=38, url="")
    reviewImage136 = ReviewImage(review_id=38, url="")
    reviewImage137 = ReviewImage(review_id=38, url="")
    reviewImage138 = ReviewImage(review_id=39, url="")
    reviewImage139 = ReviewImage(review_id=39, url="")
    reviewImage140 = ReviewImage(review_id=39, url="")
    reviewImage141 = ReviewImage(review_id=39, url="")
    reviewImage142 = ReviewImage(review_id=40, url="")
    reviewImage143 = ReviewImage(review_id=40, url="")
    reviewImage144 = ReviewImage(review_id=40, url="")
    reviewImage145 = ReviewImage(review_id=41, url="")
    reviewImage146 = ReviewImage(review_id=41, url="")
    reviewImage147 = ReviewImage(review_id=41, url="")
    reviewImage148 = ReviewImage(review_id=41, url="")
    reviewImage149 = ReviewImage(review_id=42, url="")
    reviewImage150 = ReviewImage(review_id=42, url="")
    reviewImage151 = ReviewImage(review_id=42, url="")
    reviewImage152 = ReviewImage(review_id=43, url="")
    reviewImage153 = ReviewImage(review_id=43, url="")
    reviewImage154 = ReviewImage(review_id=43, url="")
    reviewImage155 = ReviewImage(review_id=44, url="")
    reviewImage156 = ReviewImage(review_id=44, url="")
    reviewImage157 = ReviewImage(review_id=44, url="")
    reviewImage158 = ReviewImage(review_id=44, url="")
    reviewImage159 = ReviewImage(review_id=45, url="")
    reviewImage160 = ReviewImage(review_id=45, url="")
    reviewImage161 = ReviewImage(review_id=45, url="")
    reviewImage162 = ReviewImage(review_id=46, url="")
    reviewImage163 = ReviewImage(review_id=46, url="")
    reviewImage164 = ReviewImage(review_id=46, url="")
    reviewImage165 = ReviewImage(review_id=46, url="")
    reviewImage166 = ReviewImage(review_id=47, url="")
    reviewImage167 = ReviewImage(review_id=47, url="")
    reviewImage168 = ReviewImage(review_id=47, url="")
    reviewImage169 = ReviewImage(review_id=48, url="")
    reviewImage170 = ReviewImage(review_id=48, url="")
    reviewImage171 = ReviewImage(review_id=48, url="")
    reviewImage172 = ReviewImage(review_id=48, url="")
    reviewImage173 = ReviewImage(review_id=49, url="")
    reviewImage174 = ReviewImage(review_id=49, url="")
    reviewImage175 = ReviewImage(review_id=49, url="")
    reviewImage176 = ReviewImage(review_id=50, url="")
    reviewImage177 = ReviewImage(review_id=50, url="")
    reviewImage178 = ReviewImage(review_id=50, url="")
    reviewImage179 = ReviewImage(review_id=50, url="")
    reviewImage180 = ReviewImage(review_id=51, url="")
    reviewImage181 = ReviewImage(review_id=51, url="")
    reviewImage182 = ReviewImage(review_id=51, url="")
    reviewImage183 = ReviewImage(review_id=52, url="")
    reviewImage184 = ReviewImage(review_id=52, url="")
    reviewImage185 = ReviewImage(review_id=52, url="")
    reviewImage186 = ReviewImage(review_id=52, url="")
    reviewImage187 = ReviewImage(review_id=53, url="")
    reviewImage188 = ReviewImage(review_id=53, url="")
    reviewImage189 = ReviewImage(review_id=53, url="")
    reviewImage190 = ReviewImage(review_id=54, url="")
    reviewImage191 = ReviewImage(review_id=54, url="")
    reviewImage192 = ReviewImage(review_id=54, url="")
    reviewImage193 = ReviewImage(review_id=54, url="")
    reviewImage194 = ReviewImage(review_id=55, url="")
    reviewImage195 = ReviewImage(review_id=55, url="")
    reviewImage196 = ReviewImage(review_id=55, url="")
    reviewImage197 = ReviewImage(review_id=56, url="")
    reviewImage198 = ReviewImage(review_id=56, url="")
    reviewImage199 = ReviewImage(review_id=56, url="")
    reviewImage200 = ReviewImage(review_id=56, url="")
    reviewImage201 = ReviewImage(review_id=57, url="")
    reviewImage202 = ReviewImage(review_id=57, url="")
    reviewImage203 = ReviewImage(review_id=57, url="")
    reviewImage204 = ReviewImage(review_id=58, url="")
    reviewImage205 = ReviewImage(review_id=58, url="")
    reviewImage206 = ReviewImage(review_id=58, url="")
    reviewImage207 = ReviewImage(review_id=58, url="")
    reviewImage208 = ReviewImage(review_id=59, url="")
    reviewImage209 = ReviewImage(review_id=59, url="")
    reviewImage210 = ReviewImage(review_id=59, url="")
    reviewImage211 = ReviewImage(review_id=60, url="")
    reviewImage212 = ReviewImage(review_id=60, url="")
    reviewImage213 = ReviewImage(review_id=60, url="")
    reviewImage214 = ReviewImage(review_id=60, url="")
    reviewImage215 = ReviewImage(review_id=61, url="")
    reviewImage216 = ReviewImage(review_id=61, url="")
    reviewImage217 = ReviewImage(review_id=61, url="")
    reviewImage218 = ReviewImage(review_id=62, url="")
    reviewImage219 = ReviewImage(review_id=62, url="")
    reviewImage220 = ReviewImage(review_id=62, url="")
    reviewImage221 = ReviewImage(review_id=62, url="")
    reviewImage222 = ReviewImage(review_id=63, url="")
    reviewImage223 = ReviewImage(review_id=63, url="")
    reviewImage224 = ReviewImage(review_id=63, url="")
    reviewImage225 = ReviewImage(review_id=64, url="")
    reviewImage226 = ReviewImage(review_id=64, url="")
    reviewImage227 = ReviewImage(review_id=64, url="")
    reviewImage228 = ReviewImage(review_id=64, url="")
    reviewImage229 = ReviewImage(review_id=65, url="")
    reviewImage230 = ReviewImage(review_id=65, url="")
    reviewImage231 = ReviewImage(review_id=65, url="")
    # reviewImage232 = ReviewImage(review_id=66, url="")
    # reviewImage233 = ReviewImage(review_id=66, url="")
    # reviewImage234 = ReviewImage(review_id=66, url="")
    # reviewImage235 = ReviewImage(review_id=66, url="")
    # reviewImage236 = ReviewImage(review_id=67, url="")
    # reviewImage237 = ReviewImage(review_id=67, url="")
    # reviewImage238 = ReviewImage(review_id=67, url="")
    # reviewImage240 = ReviewImage(review_id=68, url="")
    # reviewImage241 = ReviewImage(review_id=68, url="")
    # reviewImage242 = ReviewImage(review_id=68, url="")
    # reviewImage243 = ReviewImage(review_id=68, url="")
    # reviewImage244 = ReviewImage(review_id=69, url="")
    # reviewImage245 = ReviewImage(review_id=69, url="")
    # reviewImage246 = ReviewImage(review_id=69, url="")
    # reviewImage247 = ReviewImage(review_id=70, url="")
    # reviewImage248 = ReviewImage(review_id=70, url="")
    # reviewImage249 = ReviewImage(review_id=70, url="")
    # reviewImage250 = ReviewImage(review_id=70, url="")
    # reviewImage251 = ReviewImage(review_id=, url="")
    # reviewImage252 = ReviewImage(review_id=, url="")
    # reviewImage253 = ReviewImage(review_id=, url="")
    # reviewImage254 = ReviewImage(review_id=, url="")
    # reviewImage255 = ReviewImage(review_id=, url="")
    # reviewImage256 = ReviewImage(review_id=, url="")
    # reviewImage257 = ReviewImage(review_id=, url="")
    # reviewImage258 = ReviewImage(review_id=, url="")
    # reviewImage259 = ReviewImage(review_id=, url="")
    # reviewImage260 = ReviewImage(review_id=, url="")
    # reviewImage261 = ReviewImage(review_id=, url="")
    # reviewImage262 = ReviewImage(review_id=, url="")
    # reviewImage263 = ReviewImage(review_id=, url="")
    # reviewImage264 = ReviewImage(review_id=, url="")
    # reviewImage265 = ReviewImage(review_id=, url="")
    # reviewImage266 = ReviewImage(review_id=, url="")
    # reviewImage267 = ReviewImage(review_id=, url="")
    # reviewImage268 = ReviewImage(review_id=, url="")
    # reviewImage269 = ReviewImage(review_id=, url="")
    # reviewImage270 = ReviewImage(review_id=, url="")
    # reviewImage271 = ReviewImage(review_id=, url="")
    # reviewImage272 = ReviewImage(review_id=, url="")
    # reviewImage273 = ReviewImage(review_id=, url="")
    # reviewImage274 = ReviewImage(review_id=, url="")
    # reviewImage275 = ReviewImage(review_id=, url="")
    # reviewImage276 = ReviewImage(review_id=, url="")
    # reviewImage277 = ReviewImage(review_id=, url="")
    # reviewImage278 = ReviewImage(review_id=, url="")
    # reviewImage279 = ReviewImage(review_id=, url="")
    # reviewImage280 = ReviewImage(review_id=, url="")
    # reviewImage281 = ReviewImage(review_id=, url="")
    # reviewImage282 = ReviewImage(review_id=, url="")
    # reviewImage283 = ReviewImage(review_id=, url="")
    # reviewImage284 = ReviewImage(review_id=, url="")
    # reviewImage285 = ReviewImage(review_id=, url="")
    # reviewImage286 = ReviewImage(review_id=, url="")
    # reviewImage287 = ReviewImage(review_id=, url="")
    # reviewImage288 = ReviewImage(review_id=, url="")
    # reviewImage289 = ReviewImage(review_id=, url="")
    # reviewImage290 = ReviewImage(review_id=, url="")
    # reviewImage291 = ReviewImage(review_id=, url="")
    # reviewImage292 = ReviewImage(review_id=, url="")
    # reviewImage293 = ReviewImage(review_id=, url="")
    # reviewImage294 = ReviewImage(review_id=, url="")
    # reviewImage295 = ReviewImage(review_id=, url="")
    # reviewImage296 = ReviewImage(review_id=, url="")
    # reviewImage297 = ReviewImage(review_id=, url="")
    # reviewImage298 = ReviewImage(review_id=, url="")
    # reviewImage299 = ReviewImage(review_id=, url="")
    # reviewImage301 = ReviewImage(review_id=, url="")
    # reviewImage302 = ReviewImage(review_id=, url="")
    # reviewImage303 = ReviewImage(review_id=, url="")
    # reviewImage304 = ReviewImage(review_id=, url="")
    # reviewImage305 = ReviewImage(review_id=, url="")
    # reviewImage306 = ReviewImage(review_id=, url="")
    # reviewImage307 = ReviewImage(review_id=, url="")
    # reviewImage307 = ReviewImage(review_id=, url="")
    # reviewImage308 = ReviewImage(review_id=, url="")
    # reviewImage308 = ReviewImage(review_id=, url="")
    # reviewImage309 = ReviewImage(review_id=, url="")
    # reviewImage309 = ReviewImage(review_id=, url="")
    # reviewImage310 = ReviewImage(review_id=, url="")
    # reviewImage310 = ReviewImage(review_id=, url="")
    # reviewImage311 = ReviewImage(review_id=, url="")
    # reviewImage311 = ReviewImage(review_id=, url="")
    # reviewImage312 = ReviewImage(review_id=, url="")
    # reviewImage312 = ReviewImage(review_id=, url="")
    # reviewImage313 = ReviewImage(review_id=, url="")
    # reviewImage313 = ReviewImage(review_id=, url="")
    # reviewImage314 = ReviewImage(review_id=, url="")
    # reviewImage314 = ReviewImage(review_id=, url="")
    # reviewImage315 = ReviewImage(review_id=, url="")
    # reviewImage315 = ReviewImage(review_id=, url="")
    # reviewImage316 = ReviewImage(review_id=, url="")
    # reviewImage316 = ReviewImage(review_id=, url="")
    # reviewImage317 = ReviewImage(review_id=, url="")
    # reviewImage317 = ReviewImage(review_id=, url="")
    # reviewImage318 = ReviewImage(review_id=, url="")
    # reviewImage318 = ReviewImage(review_id=, url="")
    # reviewImage319 = ReviewImage(review_id=, url="")
    # reviewImage319 = ReviewImage(review_id=, url="")
    # reviewImage320 = ReviewImage(review_id=, url="")
    # reviewImage320 = ReviewImage(review_id=, url="")
    # reviewImage320 = ReviewImage(review_id=, url="")
    # reviewImage321 = ReviewImage(review_id=, url="")
    # reviewImage321 = ReviewImage(review_id=, url="")
    # reviewImage322 = ReviewImage(review_id=, url="")
    # reviewImage322 = ReviewImage(review_id=, url="")
    # reviewImage323 = ReviewImage(review_id=, url="")
    # reviewImage323 = ReviewImage(review_id=, url="")
    # reviewImage324 = ReviewImage(review_id=, url="")
    # reviewImage324 = ReviewImage(review_id=, url="")
    # reviewImage325 = ReviewImage(review_id=, url="")
    # reviewImage325 = ReviewImage(review_id=, url="")
    # reviewImage326 = ReviewImage(review_id=, url="")
    # reviewImage326 = ReviewImage(review_id=, url="")
    # reviewImage327 = ReviewImage(review_id=, url="")
    # reviewImage327 = ReviewImage(review_id=, url="")
    # reviewImage328 = ReviewImage(review_id=, url="")
    # reviewImage328 = ReviewImage(review_id=, url="")
    # reviewImage329 = ReviewImage(review_id=, url="")
    # reviewImage329 = ReviewImage(review_id=, url="")
    # reviewImage330 = ReviewImage(review_id=, url="")
    # reviewImage330 = ReviewImage(review_id=, url="")
    # reviewImage331 = ReviewImage(review_id=, url="")
    # reviewImage331 = ReviewImage(review_id=, url="")
    # reviewImage332 = ReviewImage(review_id=, url="")
    # reviewImage332 = ReviewImage(review_id=, url="")
    # reviewImage333 = ReviewImage(review_id=, url="")
    # reviewImage333 = ReviewImage(review_id=, url="")
    # reviewImage334 = ReviewImage(review_id=, url="")
    # reviewImage334 = ReviewImage(review_id=, url="")
    # reviewImage335 = ReviewImage(review_id=, url="")
    # reviewImage335 = ReviewImage(review_id=, url="")
    # reviewImage336 = ReviewImage(review_id=, url="")
    # reviewImage336 = ReviewImage(review_id=, url="")
    # reviewImage337 = ReviewImage(review_id=, url="")
    # reviewImage337 = ReviewImage(review_id=, url="")

# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't

# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_reviews():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.reviews RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM reviews")

    db.session.commit()
